### ISSUE TITLE
Issue interacting with contract

### ISSUE THREAD

**Issue by ConsenSys-Academy** [GianGuaz256/blockchain-developer-bootcamp-final-project#1]
Hi there @GianGuaz256 ! 

We're having trouble interacting with your contract. Unfortunately, we can't grade it if we can't interact with it.

Two main issues:

1) It looks as though the user needs to be on Polygon before being able to access your application, but we don't see that on your frontend. Would you be able to add instructions to your README?

2) Once we do add Polygon, we're getting this error when we try to submit a transaction:

![Screen Shot 2021-11-22 at 2 00 07 PM](https://user-images.githubusercontent.com/41963038/142927099-c0c0ee44-57ad-4cd1-a383-e2dd09f4bb61.png)

Would you be able to e-mail coogan.brennan@consensys.net with any questions or follow-up?

Please let us know when this is fixed so we can try to grade this again!

**Comment by ConsenSys-Academy** [comment]
One more thing, your test suite requires ganache-cli to be running on port 8545, that should be in your README instructions as well.

**Comment by GianGuaz256** [comment]
Hello there! I've fixed this issue deploying the contract on testnet (Ropsten) and fixing the README in order to give the user instruction on how to run test locally! Thanks
